In [2]:
import seaborn as sns

In [3]:
tips = sns.load_dataset('tips')

In [4]:
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [5]:
type(tips)

pandas.core.frame.DataFrame

In [15]:
tips[['day', 'sex']]

day     sex
0     Sun  Female
1     Sun    Male
2     Sun    Male
3     Sun    Male
4     Sun  Female
..    ...     ...
239   Sat    Male
240   Sat  Female
241   Sat    Male
242   Sat    Male
243  Thur  Female

[244 rows x 2 columns]

In [8]:
print(tips['size'])

0      2
1      3
2      3
3      2
4      4
      ..
239    3
240    2
241    2
242    2
243    2
Name: size, Length: 244, dtype: int64


In [18]:
tips.index

RangeIndex(start=0, stop=244, step=1)

In [19]:
tips.dtypes

total_bill     float64
tip            float64
sex           category
smoker        category
day           category
time          category
size             int64
dtype: object

In [20]:
tips.shape

(244, 7)

In [21]:
mpg = sns.load_dataset('mpg')

In [22]:
mpg.shape

(398, 9)

In [23]:
mpg.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight            int64
acceleration    float64
model_year        int64
origin           object
name             object
dtype: object

In [24]:
mpg.info() # memory usage: 28.1+ KB -> 한꺼번에 메모리에 올린다.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64  
 7   origin        398 non-null    object 
 8   name          398 non-null    object 
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB


In [25]:
tips['total_bill'].sum(axis = 0)

4827.77

# analysis

In [26]:
import numpy as np
np.loadtxt
np.genfromtxt

<function numpy.genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=" !#$%&'()*+,-./:;<=>?@[\\]^{|}~", replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes', *, ndmin=0, like=None)>

In [27]:
np.load

<function numpy.load(file, mmap_mode=None, allow_pickle=False, fix_imports=True, encoding='ASCII', *, max_header_size=10000)>

In [28]:
import pandas as pd

In [31]:
np.lookfor('unique')

Search results for 'unique'
---------------------------
numpy.unique
    Find the unique elements of an array.
numpy.union1d
    Find the union of two arrays.
numpy.setxor1d
    Find the set exclusive-or of two arrays.
numpy.ma.unique
    Finds the unique elements of an array.
numpy.setdiff1d
    Find the set difference of two arrays.
numpy.intersect1d
    Find the intersection of two arrays.
numpy.ma.setxor1d
    Set exclusive-or of 1-D arrays with unique elements.
numpy.array_api.unique_all
    Array API compatible wrapper for :py:func:`np.unique <numpy.unique>`.
numpy.ma.setdiff1d
    Set difference of 1D arrays with unique elements.
numpy.ma.intersect1d
    Returns the unique elements common to both arrays.
numpy.array_api.unique_values
    Array API compatible wrapper for :py:func:`np.unique <numpy.unique>`.
numpy.array_api.unique_inverse
    Array API compatible wrapper for :py:func:`np.unique <numpy.unique>`.
numpy.pad
    Pad an array.
numpy.in1d
    Test whether each element o

In [33]:
from itertools import accumulate, count

In [ ]:
np.unique()


In [35]:
# __array__ : numpy와 연동된다. duck-typing

In [ ]:
# .nunique()
# .unique()

In [36]:
import seaborn as sns

In [37]:
tips = sns.load_dataset('tips')

In [38]:
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [39]:
'__iter__' in dir(tips)

True

In [40]:
a = np.arange(24).reshape(4,6)

In [41]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [42]:
for i in a:
    print(i)

[0 1 2 3 4 5]
[ 6  7  8  9 10 11]
[12 13 14 15 16 17]
[18 19 20 21 22 23]


In [43]:
a.flat # next()

In [44]:
for i in tips:
    print(i)

total_bill
tip
sex
smoker
day
time
size


In [49]:
for i in tips.itertuples(): # named tuple
    print(i)

Pandas(Index=0, total_bill=16.99, tip=1.01, sex='Female', smoker='No', day='Sun', time='Dinner', size=2)
Pandas(Index=1, total_bill=10.34, tip=1.66, sex='Male', smoker='No', day='Sun', time='Dinner', size=3)
Pandas(Index=2, total_bill=21.01, tip=3.5, sex='Male', smoker='No', day='Sun', time='Dinner', size=3)
Pandas(Index=3, total_bill=23.68, tip=3.31, sex='Male', smoker='No', day='Sun', time='Dinner', size=2)
Pandas(Index=4, total_bill=24.59, tip=3.61, sex='Female', smoker='No', day='Sun', time='Dinner', size=4)
Pandas(Index=5, total_bill=25.29, tip=4.71, sex='Male', smoker='No', day='Sun', time='Dinner', size=4)
Pandas(Index=6, total_bill=8.77, tip=2.0, sex='Male', smoker='No', day='Sun', time='Dinner', size=2)
Pandas(Index=7, total_bill=26.88, tip=3.12, sex='Male', smoker='No', day='Sun', time='Dinner', size=4)
Pandas(Index=8, total_bill=15.04, tip=1.96, sex='Male', smoker='No', day='Sun', time='Dinner', size=2)
Pandas(Index=9, total_bill=14.78, tip=3.23, sex='Male', smoker='No', day

In [ ]:
tips.day.map(lambda x: 'Mon' if x == 'Sun')

In [50]:
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [53]:
tips.select_dtypes('float64')

total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [60]:
tips.filter(regex = '^FeM')

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[244 rows x 0 columns]

In [61]:
tips.loc[1:4]

total_bill   tip     sex smoker  day    time  size
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [64]:
tips.iloc[0:5]

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4