In [1]:
# array = homo + sequence
# element-wise 계산 (수학적 컨셉) -> ndarray

In [2]:
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [3]:
import numpy as np 

In [1]:
import tensorflow as tf

In [2]:
a = tf.Tensor([1,2,3])

In [3]:
# Vectorization -> 크기가 같고, 똑같은 위치에 대해서만 연산이 되는.
dir(a) # __array__ 연동 여부 확인.

['OVERLOADABLE_OPERATORS',
 '_USE_EQUALITY',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__bool__',
 '__class__',
 '__copy__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__tf_tensor__',
 '__tf_tracing_type__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_as_node_def_input',
 '_as_tf_

In [4]:
import numpy as np

In [5]:
# 데이터 선언 
# 리터럴, 인스턴스
a = np.array([1,2,3,4])

In [6]:
a # repr

array([1, 2, 3, 4])

In [8]:
print(a) # str

[1 2 3 4]


In [7]:
type(a) # 실제 데이터 타입

numpy.ndarray

In [10]:
b = np.array([[1,2,3],[4,5,6]])

In [11]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
b = np.array([[1,2,3],[4,5,'6']])

In [13]:
b

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U21')

In [21]:
b = np.array([[1,2,3],[4,5,None]])

In [22]:
b

array([[1, 2, 3],
       [4, 5, None]], dtype=object)

In [24]:
np.ScalarType
''' C와 공유하는 데이터 타입
numpy.bool_,
 numpy.complex64,
 numpy.complex128,
 numpy.clongdouble,
 numpy.float16,
 numpy.float32,
 numpy.float64,
 numpy.longdouble,
 numpy.int8,
 numpy.int16,
 numpy.int32,
 numpy.int64,
 numpy.longlong,
 numpy.timedelta64,
 numpy.datetime64,
 numpy.object_,
 numpy.bytes_,
 numpy.str_,
...
 numpy.uint16,
 numpy.uint32,
 numpy.uint64,
 numpy.ulonglong,
 numpy.void)
'''

' C와 공유하는 데이터 타입\nnumpy.bool_,\n numpy.complex64,\n numpy.complex128,\n numpy.clongdouble,\n numpy.float16,\n numpy.float32,\n numpy.float64,\n numpy.longdouble,\n numpy.int8,\n numpy.int16,\n numpy.int32,\n numpy.int64,\n numpy.longlong,\n numpy.timedelta64,\n numpy.datetime64,\n numpy.object_,\n numpy.bytes_,\n numpy.str_,\n...\n numpy.uint16,\n numpy.uint32,\n numpy.uint64,\n numpy.ulonglong,\n numpy.void)\n'

In [25]:
np.sctype2char

<function numpy.sctype2char(sctype)>

In [26]:
np.sctypeDict

{'?': numpy.bool_,
 0: numpy.bool_,
 'byte': numpy.int8,
 'b': numpy.int8,
 1: numpy.int8,
 'ubyte': numpy.uint8,
 'B': numpy.uint8,
 2: numpy.uint8,
 'short': numpy.int16,
 'h': numpy.int16,
 3: numpy.int16,
 'ushort': numpy.uint16,
 'H': numpy.uint16,
 4: numpy.uint16,
 'i': numpy.int32,
 5: numpy.int32,
 'uint': numpy.uint64,
 'I': numpy.uint32,
 6: numpy.uint32,
 'intp': numpy.int64,
 'p': numpy.int64,
 7: numpy.int64,
 'uintp': numpy.uint64,
 'P': numpy.uint64,
 8: numpy.uint64,
 'long': numpy.int64,
 'l': numpy.int64,
 'ulong': numpy.uint64,
 'L': numpy.uint64,
 'longlong': numpy.longlong,
 'q': numpy.longlong,
 9: numpy.longlong,
 'ulonglong': numpy.ulonglong,
 'Q': numpy.ulonglong,
 10: numpy.ulonglong,
 'half': numpy.float16,
 'e': numpy.float16,
 23: numpy.float16,
 'f': numpy.float32,
 11: numpy.float32,
 'double': numpy.float64,
 'd': numpy.float64,
 12: numpy.float64,
 'longdouble': numpy.longdouble,
 'g': numpy.longdouble,
 13: numpy.longdouble,
 'cfloat': numpy.complex12

In [29]:
# array는 특징이 homo이기 때문에.
a.dtype

dtype('int64')

In [30]:
b.shape

(2, 3)

In [31]:
a.shape

(4,)

In [32]:
import tensorflow as tf
b = tf.constant([1,2,3,4])

In [36]:
b.shape

(2, 3)

In [37]:
b.size

6

In [38]:
b.ndim

2

In [39]:
# shape과 dtype 확인해야 함.
# broadcasting : 묵시적 shape 변환 -> 

In [41]:
np.zeros((2,3), dtype=float)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [44]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
np.tri(4)

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [47]:
# 수학적 컨셉에 맞추기 위해서 다양한 라이브러리를 지원해준다.
from pprint import pprint

In [48]:
pprint(tf.constant([1,2,3,4]))

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>


In [50]:
a = np.arange(48).reshape(3,4,4)

In [52]:
a # 항상 행렬 관점 -> 3 * (4,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [54]:
import tensorflow as tf


In [55]:
(X_train, y_train), (X_test, y_test) = tf.keras.datasets.mnist.load_data()

11490434/11490434 [==============================] - 1s 0us/step


In [59]:
# 항상 Numpy로 진행되는
X_train # Ellipsis와 다른 ...을 보여준다. 

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [58]:
... # 코드에서는 기능을 한다.

Ellipsis

In [60]:
# 이미 있는 데이터를 변환시키는 데 초점을 맞춰졌기 때문에.
# 확인해야 한다. 

dir(X_train)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',

In [61]:
len(dir(X_train))

165

In [64]:
np.lookfor('sum') # Numpy 기능 구현 설명

Search results for 'sum'
------------------------
numpy.sum
    Sum of array elements over a given axis.
numpy.cumsum
    Return the cumulative sum of the elements along a given axis.
numpy.einsum
    einsum(subscripts, *operands, out=None, dtype=None, order='K',
numpy.nansum
    Return the sum of array elements over a given axis treating Not a
numpy.nancumsum
    Return the cumulative sum of array elements over a given axis treating Not a
numpy.einsum_path
    Evaluates the lowest cost contraction order for an einsum expression by
numpy.trace
    Return the sum along diagonals of the array.
numpy.ma.sum
    Return the sum of the array elements over the given axis.
numpy.bool_.sum
    Scalar method identical to the corresponding array attribute.
numpy.polyadd
    Find the sum of two polynomials.
numpy.ma.cumsum
    Return the cumulative sum of the array elements over the given axis.
numpy.logaddexp
    Logarithm of the sum of exponentiations of the inputs.
numpy.bool_.cumsum
    Scalar

In [65]:
np.info(np.einsum) # 찾아써서 설명을 이해하는게 좋다.

 einsum(*operands, out=None, optimize=False, **kwargs)

einsum(subscripts, *operands, out=None, dtype=None, order='K',
       casting='safe', optimize=False)

Evaluates the Einstein summation convention on the operands.

Using the Einstein summation convention, many common multi-dimensional,
linear algebraic array operations can be represented in a simple fashion.
In *implicit* mode `einsum` computes these values.

In *explicit* mode, `einsum` provides further flexibility to compute
other array operations that might not be considered classical Einstein
summation operations, by disabling, or forcing summation over specified
subscript labels.

See the notes and examples for clarification.

Parameters
----------
subscripts : str
    Specifies the subscripts for summation as comma separated list of
    subscript labels. An implicit (classical Einstein summation)
    calculation is performed unless the explicit indicator '->' is
    included as well as subscript labels of the precise output