In [4]:
import numpy as np

In [2]:
[1,2,3] == [1,2,3]

True

In [3]:
'a' > 'A'
# data를 datatype

True

In [6]:
a = np.array([[1,2,3], [4,5,6]])

In [7]:
a.shape

(2, 3)

In [8]:
a[None]

array([[[1, 2, 3],
        [4, 5, 6]]])

In [9]:
a[:,:,None] # 차원을 증가

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [10]:
a[...,None] # 흑백이미지 3차원으로 바꿀때.

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [11]:
# curse of dimension : 차원의 저주 -> 차원을 최대한 낮춘다. 

In [12]:
np.newaxis == None

True

In [13]:
a[None, :,:]

array([[[1, 2, 3],
        [4, 5, 6]]])

In [23]:
a = b = [1,2,3,]

In [24]:
a[0] = 2

In [25]:
c= a[:] #새로운 메모리 공간에 복사함.

In [22]:
c

[3, 2, 3]

In [26]:
import copy
aa = [[1,2],[3,4]]

In [27]:
aa

[[1, 2], [3, 4]]

In [28]:
bb = copy.deepcopy(aa)

In [29]:
bb

[[1, 2], [3, 4]]

In [30]:
cc = copy(aa)

TypeError: 'module' object is not callable

In [31]:
a = np.array([[1,2,3],[4,5,6]])

In [32]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [37]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [46]:
a.reshape(-5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [40]:
a = np.arange(24)

In [47]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [48]:
a = a.reshape(4,6)

In [49]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [50]:
b = np.arange(24)

In [53]:
b.resize((3,8))

In [54]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [55]:
c = np.arange(24)

In [56]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [57]:
c.data.f_contiguous

True

In [60]:
d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [62]:
d = c.reshape(4,6)


In [63]:
d.strides # 메모리 간격, 내부적인 메모리는 일렬로 관리되기 때문에.

(48, 8)

In [64]:
d.dtype

dtype('int64')

In [59]:
d.data.f_contiguous

False

In [68]:
d.sum(axis = 1)  # axis 1을 없애서 잔여 axis 형태로 압축.

array([ 15,  51,  87, 123])

In [69]:
x = np.arange(24).reshape(2,3,4)

In [70]:
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [72]:
x.sum(axis=2)

array([[ 6, 22, 38],
       [54, 70, 86]])

In [76]:
x = np.rec.array([('Rex', 9, 81.0), ('Fido', 3, 27.0)], dtype=[('name', 'U10'),('age', 'i4'),('weight', 'f4')])

In [77]:
x.name

array(['Rex', 'Fido'], dtype='<U10')

In [73]:
from sklearn.pipeline import Pipeline

In [74]:
from sklearn.ensemble import VotingClassifier, StackingClassifier